version: 2

builds:
  - main: .
    binary: wt
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz

changelog:
  use: github-native
